In [1]:
import numpy as np

1) Masking with Boolean Arrays:

In [2]:
arr = np.array([1,2,np.nan,4,5,np.nan])

print(np.isnan(arr))
print(arr[np.isnan(arr)])
print(arr[~np.isnan(arr)])

[False False  True False False  True]
[nan nan]
[1. 2. 4. 5.]


2) Replacing Outliers with a Specific Value:

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9])

arr[arr > 7] = 7
arr[arr < 3] = 3
print(arr)

[3 3 3 4 5 6 7 7 7]


3) Removing Duplicates:

In [4]:
arr = np.array([1,2,2,2,3,3,4,5,6,7,8,9])
print(arr)

unique_arr = np.unique(arr)
print(unique_arr)

print(set(arr))

[1 2 2 2 3 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
{np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9)}


4) Categorical Data to One-Hot Encoding:

In [5]:
categorical_arr = np.array(['A','B','C','D','E'])

numrical_arr = np.array([0,1,2,3,4])

print(categorical_arr)

one_hot_arr = np.eye(5)[numrical_arr]
print(one_hot_arr)

['A' 'B' 'C' 'D' 'E']
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


5) Data Normalization:

In [6]:
arr = np.array([10000,200000,300000,4000000,5000000])

normalized_arr = (arr - arr.min()) / (arr.max() - arr.min())
print(normalized_arr)

[0.         0.03807615 0.05811623 0.7995992  1.        ]


In [7]:
arr = np.array([1,4,20,45,0])

normalized_arr = (arr - arr.min()) / (arr.max() - arr.min())
print(normalized_arr)

[0.02222222 0.08888889 0.44444444 1.         0.        ]
