In [1]:
import numpy as np

## 1 none to np.non

In [11]:
arr = np.array([1,2,3,None,4,5,None])
print(arr)


arr[arr == None] = np.nan
print(arr)

#array([1,2,3,None,4,5,None], dtype=object)

[1 2 3 None 4 5 None]
[1 2 3 nan 4 5 nan]


In [10]:
arr[arr!=None]

array([1, 2, 3, 4, 5], dtype=object)

## 2 checking the null value

In [12]:
arr = np.array([1,2,3,np.nan,4,5,np.nan])
print(arr)

print(np.isnan(arr))

[ 1.  2.  3. nan  4.  5. nan]
[False False False  True False False  True]


## 3 Removing the null value

In [13]:
arr = np.array([1,2,3,np.nan,4,5,np.nan])
print(np.isnan(arr))
print(arr[np.isnan(arr)])
print(~np.isnan(arr))
print(arr[~np.isnan(arr)])


[False False False  True False False  True]
[nan nan]
[ True  True  True False  True  True False]
[1. 2. 3. 4. 5.]


## 4 filling null with fixed value

In [14]:
arr = np.array([1,2,3,np.nan,4,5,np.nan])
print(arr)

arr[np.isnan(arr)]=0
print(arr)

[ 1.  2.  3. nan  4.  5. nan]
[1. 2. 3. 0. 4. 5. 0.]


## 5 filling the null with average

In [15]:
arr = np.array([1,2,3,np.nan,4,5,np.nan])
print(arr)

arr[np.isnan(arr)]=np.nanmean(arr)
print(arr)

[ 1.  2.  3. nan  4.  5. nan]
[1. 2. 3. 3. 4. 5. 3.]
