In [1]:
import numpy as np
arr = np.random.randint(1,11,size=(5,5))
arr

array([[ 5,  4,  6,  1,  1],
       [ 8,  9,  6,  5,  4],
       [ 2,  7,  5,  7,  9],
       [ 8,  7,  1, 10,  9],
       [10,  2, 10,  3,  6]], dtype=int32)

## 1) Filtering Data:

## 1.1) Filtering Elements Greater Than 5

In [2]:
arr[arr>5]

array([ 6,  8,  9,  6,  7,  7,  9,  8,  7, 10,  9, 10, 10,  6],
      dtype=int32)

##1.2) Filtering Even ElementS

In [3]:
arr[arr%2 == 0]

array([ 4,  6,  8,  6,  4,  2,  8, 10, 10,  2, 10,  6], dtype=int32)

1.3)Filtering Elements Meeting Multiple Conditions: 

In [5]:
arr[(arr>5) & (arr%2 == 0)]

array([ 6,  8,  6,  8, 10, 10, 10,  6], dtype=int32)

1.4) Filtering Elements Based on Division BY EITHER 3 OR 7

In [6]:
arr[(arr % 3 == 0) | (arr % 7 == 0)]

array([6, 9, 6, 7, 7, 9, 7, 9, 3, 6], dtype=int32)

1.5) Filtering Based on Conditions of Another Array 

In [7]:
arr1 = np.array([True, False, True,False,True])
arr[arr1]

array([[ 5,  4,  6,  1,  1],
       [ 2,  7,  5,  7,  9],
       [10,  2, 10,  3,  6]], dtype=int32)

1.6) Filtering Based on Specific Row Conditions:

In [9]:
filtered_arr = arr[2][arr[2,:] > 5]
filtered_arr

array([7, 7, 9], dtype=int32)

## 2) Aggregating Data:

2.1) summation

In [10]:
arr = np.array([1,2,3,4,5])
print(np.sum(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.sum(arr))
print(np.sum(arr, axis = 0))
print(np.sum(arr, axis = 1))

15
21
[5 7 9]
[ 6 15]


2.2) mean

In [11]:
arr = np.array([1,2,3,4,5])
print(np.mean(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.mean(arr))
print(np.mean(arr, axis = 0))
print(np.mean(arr, axis = 1))

3.0
3.5
[2.5 3.5 4.5]
[2. 5.]


2.3) standerd deviation

In [12]:
arr = np.array([1,2,3,4,5])
print(np.std(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.std(arr))
print(np.std(arr, axis = 0))
print(np.std(arr, axis = 1))

1.4142135623730951
1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]


2.4) Minimum and Maximum:

In [14]:
print("minimum")
arr = np.array([1,2,3,4,5])
print(np.min(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.min(arr))
print(np.min(arr, axis = 0))
print(np.min(arr, axis = 1))

print('-'*20)

print("maximum")
arr = np.array([1,2,3,4,5])
print(np.max(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.max(arr))
print(np.max(arr, axis = 0))
print(np.max(arr, axis = 1))

minimum
1
1
[1 2 3]
[1 4]
--------------------
maximum
5
6
[4 5 6]
[3 6]
