In [1]:
import numpy as np

1) searching

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## linear search
index = np.where(arr==3)[0]
print(index)

## binary search
index = np.searchsorted(arr,3)
print(index)

## searching closest value

index = np.argmin(abs(arr-11))
print(index)

[2]
2
8


2) sorting

In [5]:
arr = np.array([5,7,9,0,3,1,6,2,4,8])

# Quick sort
sorted_arr = np.sort(arr)
print(sorted_arr)

## quick sort
sorted_arr = np.sort(arr,kind='quicksort')
print(sorted_arr)

## marge sort
sorted_arr = np.sort(arr, kind = 'mergesort')
print(sorted_arr)

## heap sort
sorted_arr = np.sort(arr, kind = 'heapsort')
print(sorted_arr)


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
