In [1]:
import numpy as np

## 1 textfile

In [2]:
data = np.loadtxt('data.txt')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]


## 2 npy

In [3]:
data = np.load('data.npy')
print(data)

[[1 2 3]
 [4 5 6]]


## 3 csv

In [8]:
data = np.loadtxt('data.csv')
print(data)

ValueError: could not convert string '1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00' to float64 at row 0, column 1.

## 4 json

In [10]:
data = np.loadtxt('data.json', delimiter =',')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]


## 5 yaml

In [12]:
data = np.loadtxt('data.yaml', delimiter =',')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]
